export enum ChainsActionTypes {
    SET_CURRENT_CHAINS = 'Chains/SET_CURRENT_CHAINS',
    SET_IS_LOADING_CURRENT_CHAINS = 'Chains/SET_IS_LOADING_CURRENT_CHAINS',
    SET_CURRENT_ERROR_MESSAGE = 'Chains/SET_CURRENT_ERROR_MESSAGE',
}